### ISSUE TITLE
Travis: cache bundler and bin

### ISSUE THREAD

**Issue by toy** [toy/image_optim#113]

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I just noticed that Travis `cache:` was enabled by this commit/pull request, whereas [Travis caching feature was available since December 17, 2014](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure) (about a year before). I am interested in understanding the reason behind delaying the `cache` feature in this repository.

Thank you.

**Comment by toy** [comment]
If I understand your question right and you are asking me why didn't I add caching on CI 6 years ago and did it 5 years ago, then the answer is that I don't think that I can recall that.

**Comment by Taher-Ghaleb** [comment]
Thank you so much, @toy, for responding and sorry for any inconvenience caused.
