### ISSUE TITLE
Cannot load YAML config file that uses Range class in Ruby 3.1.x / Psych4.x

### ISSUE THREAD

**Issue by oscillot** [toy/image_optim#203]
Hello, we are in the process of updating a project to Ruby 3.1.2, and in the course of doing so ran into an issue with ImageOptim.

Once you upgrade to ruby 3.1 you also get Psych4. Psych4 changes the `load` and `load_file` methods from aliasing `unsafe_*` methods to `safe_*` methods. Psych uses a [default permit list ](https://ruby-doc.org/stdlib-3.1.0/libdoc/psych/rdoc/Psych.html) that does not include the `Range` class. As a result the config file is not loaded at all as the ImageOptim::Config class is instantiated.

Please see this repository where I have reproduced the issue with as few external components as possible: https://github.com/oscillot/image_optim_ruby_3.1_psych_4_repro

I believe all of this to be correct, however please let me know if I have missed something obvious.

If this project is amenable to it, I can submit a pull request that passes the Range class in the keyword argument `permitted_classes` that can be passed to `load` and `load_file` in these new versions.

There is some more context here that I found helpful in informing my investigation: https://www.ctrl.blog/entry/ruby-psych4.html

**Comment by toy** [comment]
Thank you for opening the issue.

Looks correct, affected is [`YAML.load_file` in `ImageOptim::Config.read_options`](https://github.com/toy/image_optim/blob/09ef8921c30a3976b7af2ac77e8ea075fbf6f7be/lib/image_optim/config.rb#L36).
Also just passing `permitted_classes` will not work: before ruby 2.3 `YAML.load_file` had only one argument, before 2.5 second argument would become the `fallback` for when the file is empty and till 3.1 `fallback` is accepted as the only keyword argument and using `permitted_classes` would error. All that is if bundled psych version is used.
I noticed possible solution in checking for presence of `YAML.safe_load_file` method (introduced in [psych 3.2.1](https://github.com/ruby/psych/releases/tag/v3.2.1)) and use that with `permitted_classes` otherwise `YAML.load_file`. Do you have an idea for a better solution? And PR is certainly welcome :)

**Comment by oscillot** [comment]
Thanks for the quick reply, @toy. That all makes sense to me, we have a versioned api with some breaking changes, we need to correctly support all versions of the api that correspond to the ruby/psych versions that the gem supports. I will try and get something together that adds compatibility for the changes without regressing on any of the old versions.
