### ISSUE TITLE
Recursive directories via command line

### ISSUE THREAD

**Issue by jakemauer** [toy/image_optim#4]
Hey Ivan, 

First thank you so much for your work on this. 

Is there a way to target multiple directories or recurse through directories and compress all images within?

**Comment by bloodymind** [comment]
Hi all ,

Please i have you probleme when typing : image_optim *.{jpg,png,gif,svg} on my shell

i got this : 

WARN: advpng 1.15 at /usr/bin/advpng (< 1.17) does not use zopfli
WARN: gifsicle 1.60 at /usr/bin/gifsicle (< 1.85) does not support removing extension blocks
Bin resolving errors:
pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options)
pngquant worker: didn't get version of pngquant ? at /usr/local/bin/pngquant; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)


Can you help me please ?

Thank you

**Comment by toy** [comment]
@bloodymind Simplest way to get up-to-date versions of nearly all binaries is by installing `image_optim_pack` gem, the only requirement is operation system — linux or osx.
If you are using it for a project using bundler, you may want to add it to `Gemfile`.
Also `pngout` is not yet packed due to license, so you need to [download it manually](http://www.jonof.id.au/kenutils) and put it somewhere on path.

Otherwise please check [binaries installation section](https://github.com/toy/image_optim#binaries-installation) in readme.

**Comment by bloodymind** [comment]
Hi @toy ,

That's working now :+1: 

Thank you.
